id: I68395C1D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T22:50:16+00:00'
last_modified: '2022-06-10T05:11:56.318698+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4522
  title: ཚད་མའི་རིགས་ལམ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    08A4:
      image_group_id: I1KG4541
      title: Volume 1 of tshad ma'i rigs lam
      total_pages: 162
      order: 1
      base_file: 08A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
